buildpacks = [
  { id = "io.projectriff.java",            latest = true, uri = "https://storage.googleapis.com/projectriff/java-function-buildpack/latest.tgz" },
  { id = "io.projectriff.node",            latest = true, uri = "https://storage.googleapis.com/projectriff/node-function-buildpack/latest.tgz" },
  { id = "io.projectriff.command",         latest = true, uri = "https://storage.googleapis.com/projectriff/command-function-buildpack/latest.tgz" },
  { id = "org.cloudfoundry.openjdk",       latest = true, uri = "https://repo.spring.io/libs-milestone-local/org/cloudfoundry/openjdk/org.cloudfoundry.openjdk/1.0.0-M8/org.cloudfoundry.openjdk-1.0.0-M8.tgz" },
  { id = "org.cloudfoundry.buildsystem",   latest = true, uri = "https://repo.spring.io/libs-milestone-local/org/cloudfoundry/buildsystem/org.cloudfoundry.buildsystem/1.0.0-M8/org.cloudfoundry.buildsystem-1.0.0-M8.tgz" },
  { id = "org.cloudfoundry.nodejs-engine", latest = true, uri = "https://github.com/cloudfoundry/node-engine-cnb/releases/download/v0.0.10/node-engine-cnb-0.0.10.tgz" },
  { id = "org.cloudfoundry.npm",           latest = true, uri = "https://github.com/cloudfoundry/npm-cnb/releases/download/v0.0.8/npm-cnb-0.0.8.tgz" },
]

[[groups]]
  # java functions
  buildpacks = [
    { id = "org.cloudfoundry.openjdk",     version = "latest", optional = true },
    { id = "org.cloudfoundry.buildsystem", version = "latest", optional = true },
    { id = "io.projectriff.java",          version = "latest" },
  ]

[[groups]]
  # node functions
  buildpacks = [
    { id = "org.cloudfoundry.nodejs-engine", version = "latest", optional = true },
    { id = "org.cloudfoundry.npm",           version = "latest", optional = true },
    { id = "io.projectriff.node",            version = "latest" },
  ]

[[groups]]
  # command functions
  buildpacks = [
    { id = "io.projectriff.command", version = "latest" },
  ]

[stack]
  id = "io.buildpacks.stacks.bionic"
  build-image = "cnbs/build"
  run-image = "cnbs/run"
