[[buildpacks]]
id = "io.projectriff.riff"
uri = "https://storage.googleapis.com/projectriff/riff-buildpack/latest.tgz"

[[buildpacks]]
id = "org.cloudfoundry.buildsystem"
uri = "https://repo.spring.io/libs-snapshot/org/cloudfoundry/buildsystem/org.cloudfoundry.buildsystem/1.0.0-BUILD-SNAPSHOT/org.cloudfoundry.buildsystem-1.0.0-BUILD-20180921.204046-1.tgz"

[[buildpacks]]
id = "org.cloudfoundry.openjdk"
uri = "https://repo.spring.io/libs-snapshot/org/cloudfoundry/openjdk/org.cloudfoundry.openjdk/1.0.0-BUILD-SNAPSHOT/org.cloudfoundry.openjdk-1.0.0-BUILD-20180921.211503-1.tgz"

[[buildpacks]]
id = "org.cloudfoundry.buildpacks.nodejs"
uri = "https://github.com/cloudfoundry/nodejs-cnb/releases/download/v0.0.1-alpha/nodejs-cnb.tgz"

[[buildpacks]]
id = "org.cloudfoundry.buildpacks.npm"
uri = "https://storage.googleapis.com/projectriff/npm-buildpack/npm-cnb-c1b7bcfe0d.tgz"

[[groups]]

  [[groups.buildpacks]]
  id = "org.cloudfoundry.openjdk"
  version = "1.0.0-BUILD-SNAPSHOT"
  optional = true # Irrelevant as this buildpack's detect is a noop, but set for clarity

  [[groups.buildpacks]]
  id = "org.cloudfoundry.buildpacks.nodejs"
  version = "0.0.1"
  optional = true # Irrelevant as this buildpack's detect is a noop, but set for clarity

  [[groups.buildpacks]]
  id = "org.cloudfoundry.buildsystem"
  version = "1.0.0-BUILD-SNAPSHOT"
  optional = true

  [[groups.buildpacks]]
  id = "org.cloudfoundry.buildpacks.npm"
  version = "0.0.1"
  optional = true

  [[groups.buildpacks]]
  id = "io.projectriff.riff"
  version = "1.0.0-BUILD-SNAPSHOT"

